# fly.toml app configuration file generated for readeck-9a3e052a558fa800 on 2026-01-21T20:10:32-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'readeck-9a3e052a558fa800'
primary_region = 'yyz'

[build]
  image = 'codeberg.org/readeck/readeck:latest'

[env]
  READECK_ALLOWED_HOSTS = 'readeck-9a3e052a558fa800.fly.dev'
  READECK_DATA_DIRECTORY = '/readeck'
  READECK_LOG_LEVEL = 'info'
  READECK_SERVER_HOST = '0.0.0.0'
  READECK_SERVER_PORT = '8000'

[[mounts]]
  source = 'readeck_data'
  destination = '/readeck'
  initial_size = '1gb'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
